---
title: Statement of Purpose
description: Harvard Department of Astronomy
program: PhD Program

format:
    pdf:
        include-before-body: 
          text: \begin{multicols}{2}
        include-after-body: 
          text: \end{multicols}
---

# Summary of Objectives

{{< include /_src/introduction.md >}}

Astrophysical simulations produce domain-specific results, but their
development demands expertise across many computational and scientific
disciplines. With cultivated expertise in computational astrophysics, 
including within the [ITC](https://www.cfa.harvard.edu/people/institute-theory-and-computation), 
Harvard is uniquely prepared to drive this
moment in astronomy and train the next generation of astrophysicists. I
hope you will consider me for admission to this training as part of the
Harvard Department of Astronomy's Doctoral Program. My experience across
multiple disciplines, including scientific software development and
nonlinear dynamics, has prepared me for the interdisciplinary work of
computational astrophysics research.

# Robotics Research

{{< include /_src/robotics.md >}}

# Dynamics Research

{{< include /_src/dynamics.md >}}

{{< pagebreak >}}

# Numerical Simulations

{{< include /_src/computing.md >}}

# Research Aspirations

{{< include /_src/astronomy.md >}}

My flight dynamics simulations within NASA echo elements of Dr. Hernquist's &
Dr. Eisenstein's massive [simulation](https://www.tng-project.org) projects: both
study macro-dynamical consequences of known or hypothesized physical
laws. After conducting dynamical sensitivity studies as an engineer, I
have been encouraged to find similar methods used in astrophysics
research, such as Dr. Kannan's 
[characterization](https://ui.adsabs.harvard.edu/abs/2021MNRAS.503..336K/abstract)
of stellar feedback's impact on the rate of galactic dust ejection
during his post-doctorate tenure at Harvard. I hope to discuss similar
such studies with my advisor, and quantify the effects of other dynamical
modes, i.e. galaxy evolution's sensitivity to radiation pressure and
stellar winds, gas flows, nearby galaxy clusters, and the epoch of
reionization. I am similarly excited by the opportunity to contribute to
Dr. Chen's models of the early universe.

I am also interested in exploring how novel computational methods may advance 
modern astrophysical simulations, such as the sub-grid and model 
reduction methods developed within the [Learning the Universe](https://www.learning-the-universe.org)
collaboration. Many scientific machine learning tools are being developed within
the Julia Programming Language community. These tools helped to propel my 
graduate astrodynamics & robotics research. If my advisor found such approaches 
promising for astronomy, I would welcome opportunities to improve and integrate 
freely available codes with ITC tools.

# Future Aspirations

With leaders in computational research, astronomy, mathematics, 
and many other technical fields, Harvard is uniquely suited to drive this 
interdisciplinary moment in astronomy. I hope to have the opportunity to learn 
from this expertise as a PhD student in Harvard's Department of Astronomy.
Thank you for your consideration.

{{< pagebreak >}}