---
title: Statement of Purpose
description: UW Department of Astronomy
program: PhD Program

format:
    pdf:
        include-before-body: 
          text: \begin{multicols}{2}
        include-after-body: 
          text: \end{multicols}
---

# Summary of Objectives

{{< include /_src/introduction.md >}}

Astrophysical simulations produce domain-specific results, but their
development demands expertise across many computational and scientific
disciplines. With cultivated expertise in computational methods,
including within the [NBody
Shop](https://astro.washington.edu/n-body-shop), UW is uniquely prepared
to drive this moment in astronomy and train the next generation of
researchers. I hope you will consider me for admission to this training
as part of the UW Department of Astronomy's Doctoral Program. My
experience across multiple disciplines, including scientific software
development and nonlinear dynamics, has prepared me for the
interdisciplinary work of computational astrophysics research.

# Robotics Research

{{< include /_src/robotics.md >}}

# Dynamics Research

{{< include /_src/dynamics.md >}}

{{< pagebreak >}}

# Numerical Simulations

{{< include /_src/computing.md >}}

# Research Aspirations

{{< include /_src/astronomy.md >}}

My flight dynamics simulations within NASA echo elements of Dr. Quinn's,
Dr. McQuinn's, and Dr. Shipp's simulation studies: both explore
macro-dynamical consequences of known or hypothesized physical laws.
After conducting dynamical sensitivity studies as an engineer, I have
been encouraged to find similar methods used in astrophysics research,
such as Dr. Faerman's
[characterization](https://ui.adsabs.harvard.edu/abs/2021hst..prop16640Z/abstract)
of the impact of stellar feedback on extra-planar galactic gas ejection
during his tenure at The Hebrew University. I hope to discuss similar
such studies with my advisor, and quantify the effects of other dynamical modes, i.e.
galaxy evolution's sensitivity to radiation pressure and stellar winds,
gas flows, nearby galaxy clusters, and the epoch of reionization.

I am also interested in exploring how novel computational methods may advance 
modern astrophysical simulations, such as the 
`ChaNGa` simulation project's optimized tree-based gravity solver. Variable-step
symplectic integrators are absent from open-source ecosystems, and I am
interested in contributing this capability. In
addition to numerical algorithms, many scientific machine learning tools
are being developed within the Julia Programming Language community;
these tools helped to propel my graduate astrodynamics & robotics
research. If encouraged by my advisor, I
would welcome opportunities to integrate new scientific machine
learning capabilities with N-Body Shop codes.

# Future Aspirations

With leaders in computational research, astronomy, and many other
technical fields, the University of Washington is uniquely suited to
drive this interdisciplinary moment in astronomy. I hope to have the opportunity to learn
from this expertise as a Doctoral student in UW's Department of
Astronomy. Thank you for your consideration.

{{< pagebreak >}}