---
title: Statement of Purpose
description: UW Department of Astronomy

format:
    pdf:
        include-before-body: 
          text: \begin{multicols}{2}
        include-after-body: 
          text: \end{multicols}
---

# Summary of Objectives

{{< include /_src/introduction.md >}}

Astrophysical simulations produce domain-specific results, but their
development demands expertise across many computational and scientific
disciplines. With cultivated expertise in computational labs, and
scientific research teams, MIT is uniquely prepared to drive this moment
in astronomy and train the next generation of astrophysicists. I hope
you will consider me for admission to this training as part of the MIT
Department of Physics' Doctoral Program. My experience across multiple
disciplines, including scientific software development and nonlinear
dynamics, has prepared me for the interdisciplinary work of
computational astrophysics research.

# Robotics Research

{{< include /_src/robotics.md >}}

# Dynamics Research

{{< include /_src/dynamics.md >}}

{{< pagebreak >}}

# Numerical Simulations

{{< include /_src/computing.md >}}

# Research Aspirations

{{< include /_src/astronomy.md >}}

NASA's flight dynamics simulations echo elements of Dr. Vogelsberger's
massive astrophysical [simulations](https://www.tng-project.org); both
study macro-dynamical consequences of known or hypothesized physical
laws. After conducting dynamical sensitivity studies as an engineer, I
have been encouraged to find similar methods used in astrophysics
research, such as Dr. Josh Borrow's
[characterization](https://arxiv.org/pdf/2212.03255.pdf) of the impact
of the epoch of reionization on early galaxy formation during his
post-doctorate tenure at MIT. I hope to discuss similar such studies
with my advisor, and quantify the impact of other feedback effects, e.g.
galaxy evolution's sensitivity to radiation pressure and stellar winds,
gas flows, galaxy clustering, and possible properties of dark matter. I
am similarly excited by the opportunity to contribute to Dr. Necib's
study of dark matter, and its intersections with galactic dynamics and
structure formation.

MIT's position as a leader of astrophysics research is further
strengthened by its breadth of cultivated technical expertise, including
that within the [Julia Lab](https://julia.mit.edu). I am interested in
exploring how Julia's revolutionary modeling & simulation codes may
accelerate astrophysical simulations, and aid projects such as Dr.
Millholland's data-driven approach to stellar formation modeling. If my
advisor found similar ideas promising, I would welcome cross-department
collaborations in the pursuit of novel science.

# Future Aspirations

With leaders in computational research, physics, mathematics, and other
technical fields, MIT is uniquely suited to drive this moment in
astronomy. I hope to have the opportunity to learn from this expertise.
Thank you for your consideration.

{{< pagebreak >}}